version: '3'

services:
  backend:
    build: .
    container_name: nayzi-telegrambot
    restart: always
    ports:
      - '8003:8000'
    command: bash -c "export environment=docker.env && python manage.py migrate && python manage.py telegrambot"
    extra_hosts:
      - "host.docker.internal:host-gateway"
