version: '3'

services:
  backend:
    build: .
    container_name: nayzi-telegrambot
    restart: always
    ports:
      - '8003:8000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ./run.sh
    env_file:
      - ./bot/docker.env
    environment:
      - "PYTHONUNBUFFERED=1"
      - "LOAD_ENV=False"
