# Generated by Django 3.0.7 on 2020-07-05 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'user_service_image',
                'verbose_name_plural': 'user_service_images',
                'db_table': 'user_service_images',
            },
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('start', 'start'), ('again_start', 'again_start'), ('get_contact_us', 'get_contact_us'), ('choice_service_uncompleted', 'choice_service_uncompleted'), ('choice_service_completed', 'choice_service_completed'), ('send_information', 'send_information')], max_length=255, verbose_name='action'),
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('images', models.ManyToManyField(related_name='user_service_image', to='core.UserServiceImage', verbose_name='images')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Service', verbose_name='services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user_service',
                'verbose_name_plural': 'user_services',
                'db_table': 'user_services',
            },
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='services',
            field=models.ManyToManyField(related_name='user_services', to='core.UserService', verbose_name='services'),
        ),
    ]
