# Generated by Django 3.0.8 on 2020-07-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200705_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'unread'), (1, 'unknown'), (2, 'in_progress'), (3, 'reserved'), (4, 'no_answer'), (5, 'other')], default=0, verbose_name='status'),
        ),
    ]
